### ISSUE TITLE
关于404判断

### ISSUE THREAD

**Issue by jjf012** [h4rdy/dir_fuzz#1]
因为有些页面会做友好404，导致误判，所以可以先访问一个不存在的页面记录404页面的长度。

**Comment by h4rdy** [comment]
我刚刚看了下几个网站,他们的友好404。①是通过301或者302跳转到一个404页面，在脚本中重定向默认是Flase不允许的,这种情况不会造成误判。②显示的是友好404页面，例如qq空间。但http状态码依然是404，也不会造成误判。③你说的那种友好404，应该是存在的，暂时我还没找到具体网站，有的话可以提供给我。
